#! /bin/bash
clear
echo "Welcome to the great gamme GUESS the number"
num=$((($RANDOM % 1000)+1))
score=0
found=true
while [ "$found" = true ];
do

read number
if (( "$number" > "$num" )) ; then
echo "Too hight"
score=$((score+1))
fi
if (( "$number" < "$num" )) ; then
echo "Too low "
score=$((score+1))
fi
if (( "$number" == "$num" )) ; then
found=false
fi
done
echo "Congratulation you find the super secret number on $score trys" 
echo "Enter your name to save your score"
read name
echo "# $name                    $score #">> save.txt
echo '#############################'>>save.txt
